name: pk demo release
run-name: ${{ github.actor }} is releasing using GitHub Actions
on:
  push:
    branches:
      #      - 'main'
      - '**'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.1.1
      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -P version=${{env.fullSemVer}}
      - name: List built files
        run: |
          ls ./build/libs
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{env.fullSemVer}}",
              sha: context.sha
            })
#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag_name: ${{env.fullSemVer}}
#          prerelease: false
#          draft: false
#          files: ./build/libs/*
#          generate_release_notes: false
